-- =================================================================
-- 01_marketplace.sql — lots, bids, lot_events, settlements (master)
-- =================================================================

USE WAREHOUSE IFF_WH;
USE DATABASE IFF_SEAFOOD;
USE SCHEMA MARKETPLACE;

CREATE TABLE IF NOT EXISTS LOTS (
  LOT_ID          STRING        PRIMARY KEY,
  HARVESTER_ID    STRING,
  NATION          STRING,
  VESSEL_NAME     STRING,
  SPECIES         STRING        NOT NULL,
  GEAR            STRING,
  AREA            STRING,
  HARVESTED_AT    TIMESTAMP_NTZ,
  WEIGHT_KG       FLOAT,
  GRADE           STRING,
  STATUS          STRING        DEFAULT 'listed', -- listed|in_auction|sold|shipped|settled|cancelled
  LISTING_PRICE   FLOAT,
  DESTINATION     STRING,
  ENVELOPE        VARIANT,
  CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT      TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS LOT_EVENTS (
  EVENT_ID      STRING        PRIMARY KEY,
  LOT_ID        STRING        NOT NULL,
  EVENT_TYPE    STRING        NOT NULL,    -- HARVEST|LANDED|PROCESSED|PACKED|SHIPPED|RECEIVED|SOLD
  ACTOR_ID      STRING,
  ACTOR_ROLE    STRING,
  LOCATION      STRING,
  PAYLOAD       VARIANT,
  PREV_HASH     STRING        NOT NULL,
  EVENT_HASH    STRING        NOT NULL,
  OCCURRED_AT   TIMESTAMP_NTZ NOT NULL
);

CREATE OR REPLACE INDEX IDX_LOT_EVENTS_LOT ON LOT_EVENTS(LOT_ID, OCCURRED_AT);

CREATE TABLE IF NOT EXISTS AUCTIONS (
  AUCTION_ID        STRING        PRIMARY KEY,
  LOT_ID            STRING        NOT NULL,
  TYPE              STRING        NOT NULL,
  STARTING_PRICE    FLOAT,
  RESERVE_PRICE     FLOAT,
  STARTS_AT         TIMESTAMP_NTZ NOT NULL,
  ENDS_AT           TIMESTAMP_NTZ NOT NULL,
  SOFT_CLOSE_SECS   INT           DEFAULT 60,
  STATUS            STRING        DEFAULT 'scheduled',
  WINNING_BID_ID    STRING,
  WINNING_BUYER_ID  STRING,
  WINNING_PRICE     FLOAT,
  CREATED_BY        STRING,
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BIDS (
  BID_ID         STRING        PRIMARY KEY,
  AUCTION_ID     STRING        NOT NULL,
  BUYER_ID       STRING        NOT NULL,
  BUYER_TIER     STRING,
  PRICE          FLOAT         NOT NULL,
  QUANTITY_KG    FLOAT,
  PLACED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE         STRING        DEFAULT 'web',
  REJECTED       BOOLEAN       DEFAULT FALSE,
  REJECTION_REASON STRING
);

CREATE TABLE IF NOT EXISTS SETTLEMENTS (
  SETTLEMENT_ID  STRING        PRIMARY KEY,
  AUCTION_ID     STRING        NOT NULL,
  LOT_ID         STRING        NOT NULL,
  GROSS          FLOAT,
  PLATFORM_FEE   FLOAT,
  NATION_SHARE   FLOAT,
  HARVESTER_NET  FLOAT,
  CURRENCY       STRING        DEFAULT 'CAD',
  STATUS         STRING        DEFAULT 'pending',
  PAID_AT        TIMESTAMP_NTZ,
  STRIPE_PI_ID   STRING,
  CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
